VERSION = '0.0.1'
APPNAME = 'betweenness'

srcdir = '.'
blddir = 'build'

def set_options(ctx):
  ctx.tool_options('compiler_cxx')

def configure(ctx):
  ctx.check_tool('compiler_cxx')
  ctx.check_cxx(lib = ['glog', 'gflags'], uselib_store = 'common')
  ctx.env.CXXFLAGS += ['-O2', '-g', '-I/usr/local/include/', '-std=c++0x']
  ctx.env.append_value('LINKFLAGS', ['-L/usr/local/lib/'])


def build(bld):

  IndexList = ['BFSIndex', 'DoubleBFS', 'LandmarkedIndex', 'Zou', 'ClusteredExactIndex'];

  bld(features     = 'cxx cstaticlib',
      source       = ['Graph/DGraph.cc'],
      target       = 'DGraph',
      includes     = ['.'])

  bld(features     = 'cxx cprogram',
      source       = ['tests/DGraphTest.cc'],
      target       = 'DGraphTest',
      includes     = ['.'],
      uselib_local = ['DGraph'])

  bld(features     = 'cxx cstaticlib',
      source       = ['Index/UnboundedLCR/BFSIndex.cc'],
      target       = 'BFSIndex',
      includes     = ['.'])

  bld(features     = 'cxx cstaticlib',
      source       = ['Index/UnboundedLCR/DoubleBFS.cc'],
      target       = 'DoubleBFS',
      includes     = ['.'],
      uselib_local = '')

  bld(features     = 'cxx cstaticlib',
      source       = ['Index/UnboundedLCR/LandmarkedIndex.cc'],
      target       = 'LandmarkedIndex',
      includes     = ['.'])

  bld(features     = 'cxx cstaticlib',
      source       = ['Index/UnboundedLCR/Zou.cc'],
      target       = 'Zou',
      includes     = ['.'],
      uselib_local = '')

  bld(features     = 'cxx cstaticlib',
      source       = ['Index/UnboundedLCR/NeighbourExchange.cc'],
      target       = 'NeighbourExchange',
      includes     = ['.'],
      uselib_local = '')

  bld(features     = 'cxx cstaticlib',
      source       = ['Index/UnboundedLCR/PartialIndex.cc'],
      target       = 'Partial',
      includes     = ['.'],
      uselib_local = '')

  bld(features     = 'cxx cstaticlib',
      source       = ['Index/UnboundedLCR/ClusteredExactIndex.cc'],
      target       = 'ClusteredExactIndex',
      includes     = ['.'],
      uselib_local = '')

  bld(features     = 'cxx cprogram',
      source       = ['experiments/genStats.cc'],
      target       = 'genStats',
      includes     = ['.'],
      uselib_local = 'BFSIndex')

  bld(features     = 'cxx cprogram',
      source       = ['experiments/Index/UnboundedLCR/runExperiment.cc'],
      target       = 'runExperiment',
      includes     = ['.'],
      uselib_local = IndexList)

  bld(features     = 'cxx cprogram',
      source       = ['experiments/Index/UnboundedLCR/maintenanceExp.cc'],
      target       = 'maintenanceExp',
      includes     = ['.'],
      uselib_local = IndexList)

  bld(features     = 'cxx cprogram',
      source       = ['experiments/Index/UnboundedLCR/queryAllExp.cc'],
      target       = 'queryAllExp',
      includes     = ['.'],
      uselib_local = IndexList)

  bld(features     = 'cxx cprogram',
      source       = ['experiments/Index/UnboundedLCR/genQuery.cc'],
      target       = 'genQuery',
      includes     = ['.'],
      uselib_local = IndexList)

  bld(features     = 'cxx cprogram',
      source       = ['tests/Index/UnboundedLCR/LandmarkedIndexTest.cc'],
      target       = 'LandmarkedIndexTest',
      includes     = ['.'],
      uselib_local = ['LandmarkedIndex'])

  bld(features     = 'cxx cprogram',
      source       = ['tests/Index/UnboundedLCR/DoubleBFSTest.cc'],
      target       = 'DoubleBFSTest',
      includes     = ['.'],
      uselib_local = ['LandmarkedIndex'])

  bld(features     = 'cxx cprogram',
      source       = ['tests/Index/UnboundedLCR/BFSTest.cc'],
      target       = 'BFSTest',
      includes     = ['.'],
      uselib_local = ['LandmarkedIndex'])

  bld(features     = 'cxx cprogram',
      source       = ['tests/Index/UnboundedLCR/ZouTest.cc'],
      target       = 'ZouTest',
      includes     = ['.'],
      uselib_local = ['Zou'])

  bld(features     = 'cxx cstaticlib',
      source       = ['Index/UnboundedLCR/WD/LandmarkedIndexWD.cc'],
      target       = 'LandmarkedIndexWD',
      includes     = ['.']
      )

  bld(features     = 'cxx cprogram',
      source       = ['tests/Index/UnboundedLCR/WD/LandmarkedIndexWDTest.cc'],
      target       = 'LandmarkedIndexWDTest',
      includes     = ['.'],
      uselib_local = ['LandmarkedIndexWD']
      )

  bld(features     = 'cxx cprogram',
      source       = ['experiments/Index/UnboundedLCR/runWDExperiment.cc'],
      target       = 'runWDExperiment',
      includes     = ['.'],
      uselib_local = ['LandmarkedIndex', 'LandmarkedIndexWD'] )
